apiVersion: v1
kind: Service
metadata:
  name: recording-service
  namespace: edutrack
  labels:
    app: recording-service
    app.kubernetes.io/part-of: edutrack
spec:
  type: ClusterIP
  selector:
    app: recording-service
  ports:
    - port: 3006
      targetPort: 3006
      protocol: TCP
