apiVersion: v1
kind: Service
metadata:
  name: meeting-service
  namespace: edutrack
  labels:
    app: meeting-service
    app.kubernetes.io/part-of: edutrack
spec:
  type: ClusterIP
  selector:
    app: meeting-service
  ports:
    - port: 3005
      targetPort: 3005
      protocol: TCP
