apiVersion: v1
kind: Service
metadata:
  name: ai-chat-service
  namespace: edutrack
  labels:
    app: ai-chat-service
    app.kubernetes.io/part-of: edutrack
spec:
  type: ClusterIP
  selector:
    app: ai-chat-service
  ports:
    - port: 3007
      targetPort: 3007
      protocol: TCP
