ALTER TABLE profiles
  ADD COLUMN IF NOT EXISTS first_name VARCHAR(100),
  ADD COLUMN IF NOT EXISTS last_name VARCHAR(100),
  ALTER COLUMN full_name SET DEFAULT '';

ALTER TABLE refresh_tokens
  ADD COLUMN IF NOT EXISTS revoked BOOLEAN DEFAULT false;
