apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: edutrack
  labels:
    app: notification-service
    app.kubernetes.io/part-of: edutrack
spec:
  type: ClusterIP
  selector:
    app: notification-service
  ports:
    - port: 3008
      targetPort: 3008
      protocol: TCP
