apiVersion: v1
kind: ConfigMap
metadata:
  name: edutrack-config
  namespace: edutracklocal
data:
  NODE_ENV: "production"
  POSTGRES_DB: "edutrack"
  POSTGRES_USER: "postgres"
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  REDIS_URL: "redis://redis:6379"
  AI_PROVIDER: "built-in"
  JWT_EXPIRES_IN: "15m"
  REFRESH_TOKEN_EXPIRES_IN: "7d"
  CORS_ORIGINS: "http://localhost:5173,http://192.168.68.112:30081,https://your-frontend.example.com"
  AUTH_SERVICE_URL: "http://auth-service:3001"
  USER_SERVICE_URL: "http://user-service:3002"
  COURSE_SERVICE_URL: "http://course-service:3003"
  ASSIGNMENT_SERVICE_URL: "http://assignment-service:3004"
  MEETING_SERVICE_URL: "http://meeting-service:3005"
  RECORDING_SERVICE_URL: "http://recording-service:3006"
  AI_CHAT_SERVICE_URL: "http://ai-chat-service:3007"
  NOTIFICATION_SERVICE_URL: "http://notification-service:3008"
  SMTP_HOST: "smtp.gmail.com"
  SMTP_PORT: "587"
  SMTP_USER: ""
  FROM_EMAIL: "noreply@edutrack.local"
