apiVersion: v1
kind: Secret
metadata:
  name: edutrack-secrets
  namespace: edutracklocal
type: Opaque
stringData:
  POSTGRES_PASSWORD: "Ipmith1111112345"
  DATABASE_URL: "postgresql://postgres:Ipmith1111112345@postgres:5432/edutrack"
  JWT_SECRET: "Ipmith1111112345"
  SMTP_PASS: ""
