apiVersion: v1
kind: Secret
metadata:
  name: edutrack-secrets
  namespace: edutracklocal
type: Opaque
stringData:
  POSTGRES_PASSWORD: "Ipmith!@#$%12345"
  DATABASE_URL: "postgresql://postgres:Ipmith!@#$%12345@postgres:5432/edutrack"
  JWT_SECRET: "Ipmith!@#$%12345"
  SMTP_PASS: ""
