apiVersion: v1
kind: Secret
metadata:
  name: edutrack-secrets
  namespace: edutrack
type: Opaque
stringData:
  POSTGRES_PASSWORD: "CHANGE_ME_POSTGRES_PASSWORD"
  DATABASE_URL: "postgresql://postgres:CHANGE_ME_POSTGRES_PASSWORD@postgres:5432/edutrack"
  JWT_SECRET: "CHANGE_ME_WITH_A_LONG_RANDOM_SECRET_VALUE"
  SMTP_PASS: ""
